### PR TITLE
sim-all: Adds description to both existing creates

### PR DESCRIPTION
**Pull request by sr-gi**
Mainly so we can have something nice when running `--help`

### CODE REVIEW

**Comment by sr-gi** [comment]
Feel free to nitpick on the descriptions, I'm almost as bad as those as I am at naming things.

**Review by okjodom — APPROVED** [review]

**Review by carlaKC — APPROVED** [review]
lgtm, only nit is to end description with `.` if that's a normal thing to do (idk)

**Comment by sr-gi** [comment]
I think it does not. When in doubt I always check `bitcoind`:

```
> bitcoind --help
Bitcoin Core version v25.0.0
```

**Comment by carlaKC** [comment]
Cool, then shippin it!

**Pull request merged**
