### PR TITLE
Try to add eclair/ldk support

### PR DESCRIPTION
**Pull request by PurpleTimez**
I don't understand the framework, and dunno if other implems support can be useful.

### CODE REVIEW

**Comment by PurpleTimez** [comment]
## Eclair Support

From eclair documentation's (`README.md`), there is an API where one can install plugin written in Scala, Java or any JVM-compatible language.

I think from then a plugin could be designed to expose a GRPC interface and this interface driven by a `sim-lib` module to act sim actions (`get_info`, `send_payment`, `track_payment`, `get_node_info`, `list_channels`).

## LDK Support

LDK has a sample node called `ldk-sample`. It is a test lightning node that one can run on the command-line a REPL fashion. Internally, it's using a module (`cli.rs`) which is pipping user command to the internal interface of the LDK library.

I think a GRPC interface alternatively integrated in `ldk-sample` runtime, instead of the command-line cli could be a way to have a LDK runtime driven by `sim-lib`. Accessing directly the LDK interface allow a stable interface to act on sim actions
(`get_info`, `send_payment`, `track_payment`, `get_node_info`, `list_channels`).

I don't know if the two support approaches will work end-to-end, though I think it's an interesting way to have eclair / ldk support in `sim-ln`. I don't know how much hacking work it is, I can try.

**Comment by carlaKC** [comment]
See #26 for ongoing discussion on multi-impl support

**Comment by PurpleTimez** [comment]
> See https://github.com/bitcoin-dev-project/sim-ln/issues/26 for ongoing discussion on multi-impl support

Left thoughts here. Sounds eclair support better to prioritize. Dunno if way proposed is not too much maintenance.

**Comment by carlaKC** [comment]
Closing boilerplate PR after discussion in #26, feel free to re-open an eclair implementation [if reasonably achievable](https://github.com/bitcoin-dev-project/sim-ln/issues/26#issuecomment-2122928053).

**Pull request closed without merging**
