### PR TITLE
sim-lib: Fixes clippy issues

### PR DESCRIPTION
**Pull request by sr-gi**
Updates clippy to use maintained actions, plus fixes clippy issues.

### CODE REVIEW

**Comment by carlaKC** [comment]
What version of clippy are you on? 

I don't have any complaints on [ff9f918](https://github.com/bitcoin-dev-project/sim-ln/commit/ff9f9186c8221db7e5981c2d9474bd542d3169ed) (and neither does the CI when the last PR was merged).

**Comment by sr-gi** [comment]
`clippy 0.1.73 (cc66ad46 2023-10-03)`

**Comment by sr-gi** [comment]
I've updated the PR to switch to maintained actions given `action-rs` is now unmaintained.

**Comment by sr-gi** [comment]
> What version of clippy are you on?
> 
> I don't have any complaints on [ff9f918](https://github.com/bitcoin-dev-project/sim-ln/commit/ff9f9186c8221db7e5981c2d9474bd542d3169ed) (and neither does the CI when the last PR was merged).

Looks like new PR are: https://github.com/bitcoin-dev-project/sim-ln/actions/runs/6566476194/job/17837246558?pr=145

**Review by carlaKC — APPROVED** [review]

**Comment by carlaKC** [comment]
> Looks like new PR are: https://github.com/bitcoin-dev-project/sim-ln/actions/runs/6566476194/job/17837246558?pr=145

idk how we broke this, build passed on the original PR 🤔

**Comment by carlaKC** [comment]
> I don't think we did. The rust compiler gets updated by `actions` every now and then (I'm not sure what the schedule is) so it passed originally with the old one, and it got updated afterwards

Ah, gotcha. Weird that they don't bump the action version when they do that :')

**Pull request merged**
