### PR TITLE
chore: use published version of fedimint-tonic-lnd

### PR DESCRIPTION
**Pull request by okjodom**

### CODE REVIEW

**Review by carlaKC — APPROVED** [review]
lgtm!

**Comment by carlaKC** [comment]
> Needs a `cargo update` to get `Cargo.lock` in sync!

ping! would be nice to get this in

**Review by carlaKC — APPROVED** [review]
🧹

**Review by sr-gi — COMMENTED** [review]
tACK [dd71d68](https://github.com/bitcoin-dev-project/sim-ln/pull/137/commits/dd71d6847a36fcf6b8a0b9490cc2e34d6512d775)

**Pull request merged**
